version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - rabbit
    volumes:
      - .:/celery
  rabbit:
    hostname: rabbit
    image: rabbitmq:management
    ports:
      - "5672:5672"                   #for rabbitmq client connections
      - "15672:15672"                 #for rabbitmq manangement website
  worker:
    build:
      context: .
    hostname: worker_1
    command: celery -A flasksmtp.celery worker -l INFO
    volumes:
      - .:/celery
    links:
      - rabbit
    depends_on:
      - rabbit
